// auth
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';

// user
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE = 'CHECK_USER_FAILURE';
//quizzes
export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS';
export const FETCH_ALL_QUIZZES_REQUEST = 'FETCH_ALL_QUIZZES_REQUEST';
export const FETCH_ALL_QUIZZES_SUCCESS = 'FETCH_ALL_QUIZZES_SUCCESS';
export const FETCH_ALL_QUIZZES_FAILURE = 'FETCH_ALL_QUIZZES_FAILURE';

export const FETCH_ALL_USER_QUIZZES_REQUEST = 'FETCH_ALL_USER_QUIZZES_REQUEST';
export const FETCH_ALL_USER_QUIZZES_SUCCESS = 'FETCH_ALL_USER_QUIZZES_SUCCESS';
export const FETCH_ALL_USER_QUIZZES_FAILURE = 'FETCH_ALL_USER_QUIZZES_FAILURE';

export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';

export const FETCH_USER_QUIZ_REQUEST = 'FETCH_USER_QUIZ_REQUEST';
export const FETCH_USER_QUIZ_SUCCESS = 'FETCH_USER_QUIZ_SUCCESS';
export const FETCH_USER_QUIZ_FAILURE = 'FETCH_USER_QUIZ_FAILURE';

export const UPDATE_USER_SCORE_REQUEST = 'UPDATE_USER_SCORE_REQUEST';
export const UPDATE_USER_SCORE_SUCCESS = 'UPDATE_USER_SCORE_SUCCESS';
export const UPDATE_USER_SCORE_FAILURE = 'UPDATE_USER_SCORE_FAILURE';

export const UPDATE_USER_FAVORITE_REQUEST = 'UPDATE_USER_FAVORITE_REQUEST';
export const UPDATE_USER_FAVORITE_SUCCESS = 'UPDATE_USER_FAVORITE_SUCCESS';
export const UPDATE_USER_FAVORITE_FAILURE = 'UPDATE_USER_FAVORITE_FAILURE';

export const CREATE_QUIZ_REQUEST = 'CREATE_QUIZ_REQUEST';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILURE = 'CREATE_QUIZ_FAILURE';

export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_FAILURE = 'DELETE_QUIZ_FAILURE';

export const EDIT_QUIZ_REQUEST = 'EDIT_QUIZ_REQUEST';
export const EDIT_QUIZ_SUCCESS = 'EDIT_QUIZ_SUCCESS';
export const EDIT_QUIZ_FAILURE = 'EDIT_QUIZ_FAILURE';

//questions
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const FETCH_QUIZ_QUESTIONS_REQUEST = 'FETCH_QUIZ_QUESTIONS_REQUEST';
export const FETCH_QUIZ_QUESTIONS_SUCCESS = 'FETCH_QUIZ_QUESTIONS_SUCCESS';
export const FETCH_QUIZ_QUESTIONS_FAILURE = 'FETCH_QUIZ_QUESTIONS_FAILURE';

export const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE';

export const FETCH_QUESTION_RESULT_REQUEST = 'FETCH_QUESTION_RESULT_REQUEST';
export const FETCH_QUESTION_RESULT_SUCCESS = 'FETCH_QUESTION_RESULT_SUCCESS';
export const FETCH_QUESTION_RESULT_FAILURE = 'FETCH_QUESTION_RESULT_FAILURE';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';

//forum
export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'FETCH_ALL_POSTS_FAILURE';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
